name: 💻 Dev CI
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]


jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    name: Node $ build
    steps:
      - uses: actions/checkout@v2 
      - name: 👀 Cache node_modules 
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: $-node-$
          restore-keys: |
            $-node
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: $
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.6
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - run: pnpm run test:cov
      - name: ZIP Coverage $
        if: github.event_name == 'push'
        run: zip -r coverage.zip ./coverage
      - name: Upload Test Coverage $
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
      - name: ZIP Build Assets $
        if: github.event_name == 'push'
        run: zip -r build.zip ./dist
      - name: Upload build
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: dist
